### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by N1D4L0S** [AusTechDev/BetterReports#30]
Got this error.

[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1709)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at BetterReports-2.0.2.jar//dev.austech.betterreports.util.UpdateCheck.fetchResponse(UpdateCheck.java:127)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at BetterReports-2.0.2.jar//dev.austech.betterreports.util.UpdateCheck$1.run(UpdateCheck.java:73)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: Caused by: java.io.EOFException: SSL peer shut down incorrectly
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
[10:20:24] [Craft Scheduler Thread - 83 - BetterReports/WARN]: 	... 14 more

**Comment by mnewt00** [comment]
**Hi there!**

We apologise for this issue and we are trying our best to resolve this issue.
It should be fixed soon, however, it is out of my hands.

**Comment by mnewt00** [comment]
Our servers are working again and this issue should no longer occur.
